### ISSUE TITLE
[FEATURE REQUEST] - Would be great to have Battery Level added to read

### ISSUE THREAD

**Issue by DigiH** [Heckie75/Mipow-Playbulb-BTL201#4]
Having come across this great script and using it with my Playbulb Candles (BTL300_v5 and BTL300_v6), I am now wondering if it would be possible to add Battery Level (and possibly Battery Level State and Battery Power State - depending on other script compatible Playbulb devices not having batteries or being rechargeable). Especially with polling the battery levels regularly and automating alerts for fading battery levels, this would be very helpful.

While pondering about this possibility I found the following interesting link:
https://codelabs.developers.google.com/codelabs/candle-bluetooth/index.html?index=..%2F..index#4
stating, that the "Battery Service is not advertised by the PLAYBULB Candle Bluetooth device but still mandatory to access it through the standard names such as battery_service for the Bluetooth GATT Service UUID and battery_level for the Bluetooth GATT Characteristic UUID. 

Many thanks again for a great script!

**Comment by Heckie75** [comment]
Please give me the output of following commands:
```
gatttool -b 4C:65:A8:DA:F3:B1 -I
[4C:65:A8:DA:F3:B1][LE]> connect
Attempting to connect to 4C:65:A8:DA:F3:B1
Connection successful
```

Then query characteristics like this:
```
[4C:65:A8:DA:F3:B1][LE]> characteristics 
...
handle: 0x0017, char properties: 0x12, char value handle: 0x0018, uuid: 00002a19-0000-1000-8000-00805f9b34fb
...
```

We are looking for characteristics with uuid ```00002a19-...``` which is the Battery level.

If you have found it: What's the _char value handle_? In my example it is 0x0018

You can then try the folling:
```
[4C:65:A8:DA:F3:B1][LE]> char-read-hnd 0x0018
Characteristic value/descriptor: 3b 
```
In this example the battery level is 0x3b which is 59% in decimal.

Are there also uuids 00002A1B (battery level state) or 00002A1A (battery power state)?

If yes, what is the output if you do the same queries here?

**Comment by Heckie75** [comment]
I have commited a new version of ```mipow.exp```

Please try if you get the battery level:
```
$ mipow L dump

Device mac:                 6D:70:4B:0F:AC:E6
Device name (0021):         Lampe
Device password:            (not supported)
Battery level (0024):       (not supported)
Device vendor (0030):       Mipow Limited
```

In my case there is no output since my devices don't have a battery.

**Comment by DigiH** [comment]
My char value handle is 0x001f, giving me the result of 64, i.e. 100% charges, which fits as I actually got thinking about the possibility of having this in the your script after a rlound of charing the batteries for my Playbulb candles. I'll quickly check the other version candles and will try out the new mipow.exp version.

Thanks a lot.

**Comment by DigiH** [comment]
0x001f was from the BTL300_v5 candles, BTL300_v6 candles have 0x0022. Both versions nicely showing the Battery Level now. The battery level state and battery power state are not being shown in the characteristics of my candles. I don't have any experience with other Playbulb devices, so am not sure if some of them might be relevant with these.

> Device password:            (not supported)
Battery level (0022):       100%
Device vendor (002e):       Mipow Limited
Device id (0026):           BTL300
Device version (002a):      BTL300_v6
Device software (002c):     Application version 2.4.3.26
Device CPU (0028):          CSR101x A05

Many thanks for the quick inclusion of this. I will now set up a regular poll of the battery states to avoid dead candles when I want them on.

**Comment by Heckie75** [comment]
Perfect!
