### ISSUE TITLE
Mipow.exp on Raspberry Pi

### ISSUE THREAD

**Issue by SteampunkProfessor** [Heckie75/Mipow-Playbulb-BTL201#5]
Hi,

I'm getting this error at the moment (with logging set to on) with my Mipow string, any ideas?:
doCommand: received command <status>
[                 ][LE]> connect 1E:9D:4B:16:AC:E6
Attempting to connect to 1E:9D:4B:16:AC:E6
Connection successful
[1E:9D:4B:16:AC:E6][LE]> readBulb: char-read-hnd 0023
char-read-hnd 0023
Characteristic value/descriptor: ff 00 00 00
[1E:9D:4B:16:AC:E6][LE]> ok
ok
readBulb: 0023 ff000000
readBulb: char-read-hnd 0021
char-read-hnd 0021
Characteristic value/descriptor: ff 00 00 00 ff 00 a7 00
ok
ok
readBulb: 0021 ff000000ff00a700
readBulb: char-read-hnd 0027
[1E:9D:4B:16:AC:E6][LE]> char-read-hnd 0027
Characteristic value/descriptor: 04 ff ff 04 ff ff 04 ff ff 04 ff ff 00 00 00 00 00 00
[1E:9D:4B:16:AC:E6][LE]> ok
ok
readBulb: 0027 04ffff04ffff04ffff04ffff000000000000
readBulb: char-read-hnd 001f
char-read-hnd 001f
Characteristic value/descriptor: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[1E:9D:4B:16:AC:E6][LE]> ok
ok
readBulb: 001f 0000000000000000000000000000000000000000
can't read "HANDLES(randommode)": no such element in array
    while executing
"readBulb $HANDLES(randommode)"
    (procedure "readRandomMode" line 4)
    invoked from within
"readRandomMode"
    (procedure "init" line 20)
    invoked from within
"init [expr $INIT(color) + $INIT(effect) + $INIT(timers)]"
    ("^status$" arm line 2)
    invoked from within
"switch -regexp $c {
    ^status$ {
      init [expr $INIT(color) + $INIT(effect) + $INIT(timers)]
      printStatus
    }
    ^dump$ {
      init [exp..."
    (procedure "doCommand" line 10)
    invoked from within
"doCommand"
    ("while" body line 2)
    invoked from within
"while {$cmd != ""} {
  doCommand
}"
    (file "./mipow.exp" line 1769)

**Comment by Heckie75** [comment]
What is the model no?

Could you please provide the handle File that ist located in the /tmp directory, e.g. bulb-6A-9C-4B-0F-AC-E6.hnd?

I guess that your bulb propably does not support the randommode.

**Comment by SteampunkProfessor** [comment]
The model is BTL505-GN

The hnd file:

handle = 0x0002, char properties = 0x20, char value handle = 0x0003, uuid =
00002a05-0000-1000-800
0-00805f9b34fb
handle = 0x0006, char properties = 0x0a, char value handle = 0x0007, uuid =
00002a00-0000-1000-800
0-00805f9b34fb
handle = 0x0008, char properties = 0x02, char value handle = 0x0009, uuid =
00002a01-0000-1000-800
0-00805f9b34fb
handle = 0x000a, char properties = 0x02, char value handle = 0x000b, uuid =
00002a04-0000-1000-800
0-00805f9b34fb
handle = 0x000d, char properties = 0x0a, char value handle = 0x000e, uuid =
00001013-d102-11e1-9b2
3-00025b00a5a5
handle = 0x000f, char properties = 0x08, char value handle = 0x0010, uuid =
00001018-d102-11e1-9b2
3-00025b00a5a5
handle = 0x0011, char properties = 0x12, char value handle = 0x0012, uuid =
00001014-d102-11e1-9b2
3-00025b00a5a5
handle = 0x0014, char properties = 0x02, char value handle = 0x0015, uuid =
00001011-d102-11e1-9b2
3-00025b00a5a5
handle = 0x0017, char properties = 0x10, char value handle = 0x0018, uuid =
00002a37-0000-1000-800
0-00805f9b34fb
handle = 0x001a, char properties = 0x08, char value handle = 0x001b, uuid =
00001234-0000-1000-800
0-00805f9b34fb
handle = 0x001c, char properties = 0x0a, char value handle = 0x001d, uuid =
0000fff7-0000-1000-800
0-00805f9b34fb
handle = 0x001e, char properties = 0x02, char value handle = 0x001f, uuid =
0000fff8-0000-1000-800
0-00805f9b34fb
handle = 0x0020, char properties = 0x06, char value handle = 0x0021, uuid =
0000fffb-0000-1000-800
0-00805f9b34fb
handle = 0x0022, char properties = 0x06, char value handle = 0x0023, uuid =
0000fffc-0000-1000-800
0-00805f9b34fb
handle = 0x0024, char properties = 0x0a, char value handle = 0x0025, uuid =
0000fffd-0000-1000-800
0-00805f9b34fb
handle = 0x0026, char properties = 0x0a, char value handle = 0x0027, uuid =
0000fffe-0000-1000-800
0-00805f9b34fb
handle = 0x0028, char properties = 0x0a, char value handle = 0x0029, uuid =
0000ffff-0000-1000-800
0-00805f9b34fb
handle = 0x002a, char properties = 0x0a, char value handle = 0x002b, uuid =
0000fff5-0000-1000-800
0-00805f9b34fb
handle = 0x002d, char properties = 0x12, char value handle = 0x002e, uuid =
00002a19-0000-1000-800
0-00805f9b34fb
handle = 0x0031, char properties = 0x08, char value handle = 0x0032, uuid =
c4edc000-9daf-11e3-800
0-00025b000b00
handle = 0x0033, char properties = 0x02, char value handle = 0x0034, uuid =
c4edc000-9daf-11e3-800
1-00025b000b00
handle = 0x0035, char properties = 0x0a, char value handle = 0x0036, uuid =
c4edc000-9daf-11e3-800
2-00025b000b00
handle = 0x0037, char properties = 0x1c, char value handle = 0x0038, uuid =
c4edc000-9daf-11e3-800
3-00025b000b00
handle = 0x003a, char properties = 0x1c, char value handle = 0x003b, uuid =
c4edc000-9daf-11e3-800
4-00025b000b00
handle = 0x003d, char properties = 0x0a, char value handle = 0x003e, uuid =
c4edc000-9daf-11e3-800
5-00025b000b00
handle = 0x003f, char properties = 0x0a, char value handle = 0x0040, uuid =
c4edc000-9daf-11e3-800
6-00025b000b00
handle = 0x0042, char properties = 0x02, char value handle = 0x0043, uuid =
00002a25-0000-1000-800
0-00805f9b34fb
handle = 0x0044, char properties = 0x02, char value handle = 0x0045, uuid =
00002a27-0000-1000-800
0-00805f9b34fb
handle = 0x0046, char properties = 0x02, char value handle = 0x0047, uuid =
00002a26-0000-1000-800
0-00805f9b34fb
handle = 0x0048, char properties = 0x02, char value handle = 0x0049, uuid =
00002a28-0000-1000-800
0-00805f9b34fb
handle = 0x004a, char properties = 0x02, char value handle = 0x004b, uuid =
00002a29-0000-1000-800
0-00805f9b34fb
handle = 0x004c, char properties = 0x02, char value handle = 0x004d, uuid =
00002a50-0000-1000-800
0-00805f9b34fb


Hope that helps

**Comment by Heckie75** [comment]
Ok, it seems that your devide does not support the security / randommode. I am going to change the script so that it can face this situation.

**Comment by Heckie75** [comment]
Please check if the latest version of mipow.exp works for you now. 

Please also tell me which device do you have (model no.) so that I can add it to the list of supported devices. 

Cheers

**Comment by SteampunkProfessor** [comment]
Hi, Thanks for your quick reply and fix, it is working perfectly now. :-) It's the MiPow Playbulb String (BTL505-GN)RegardsSent from my Samsung Galaxy smartphone.
-------- Original message --------From: Heckie <notifications@github.com> Date: 11/10/2019  18:01  (GMT+00:00) To: Heckie75/Mipow-Playbulb-BTL201 <Mipow-Playbulb-BTL201@noreply.github.com> Cc: SteampunkProfessor <steampunkprofessor@gmail.com>, Author <author@noreply.github.com> Subject: Re: [Heckie75/Mipow-Playbulb-BTL201] Mipow.exp on Raspberry Pi (#5) Please check if the latest version of mipow.exp works for you now.
Please also tell me which device do you have (model no.) so that I can add it to the list of supported devices.
Cheers

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Heckie75/Mipow-Playbulb-BTL201/issues/5?email_source=notifications\u0026email_token=AAIIS4WAYJFATAS2F4G77KLQOCWPDA5CNFSM4I7FVIUKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBATM4Q#issuecomment-541144690",
"url": "https://github.com/Heckie75/Mipow-Playbulb-BTL201/issues/5?email_source=notifications\u0026email_token=AAIIS4WAYJFATAS2F4G77KLQOCWPDA5CNFSM4I7FVIUKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBATM4Q#issuecomment-541144690",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Heckie75** [comment]
Perfect, please give me a "star" if you enjoy this project.

**Comment by SteampunkProfessor** [comment]
Done :-) Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Heckie <notifications@github.com> Date: 12/10/2019  05:09  (GMT+00:00) To: Heckie75/Mipow-Playbulb-BTL201 <Mipow-Playbulb-BTL201@noreply.github.com> Cc: SteampunkProfessor <steampunkprofessor@gmail.com>, Author <author@noreply.github.com> Subject: Re: [Heckie75/Mipow-Playbulb-BTL201] Mipow.exp on Raspberry Pi (#5) Perfect, please give me a "star" if you enjoy this project.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Heckie75/Mipow-Playbulb-BTL201/issues/5?email_source=notifications\u0026email_token=AAIIS4SFHXG5BD77L7BFRI3QOFEWVA5CNFSM4I7FVIUKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBBVBEQ#issuecomment-541282450",
"url": "https://github.com/Heckie75/Mipow-Playbulb-BTL201/issues/5?email_source=notifications\u0026email_token=AAIIS4SFHXG5BD77L7BFRI3QOFEWVA5CNFSM4I7FVIUKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBBVBEQ#issuecomment-541282450",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
