### ISSUE TITLE
Homebridge support

### ISSUE THREAD

**Issue by holovashkin** [Heckie75/Mipow-Playbulb-BTL201#6]
The bulbs are pretty cool and your code works just perfect through SSH, thanks for that!

Is there any chance / plans on porting it or creating plugin for homebridge?

This way would make the bulbs available on homekit and bringing control over siri

**Comment by Heckie75** [comment]
I have no experience with homebridge or homekit. I control my bulbs by using my kodi plugin that it also available in github and by using the android app "SSH button"

**Comment by holovashkin** [comment]
Thanks for the answer and your time!

Homebridge is nodejs server that allows to add custom devices to homekit and allow siri to control them.

Do you have any ideas if the playbulbs can be controlled via BLE http protocol?
Maybe combining your code with bluetooth plugin could work.. https://www.npmjs.com/package/homebridge-bluetooth

**Comment by Heckie75** [comment]
I guess that there are plugins for homebridge in order to integrate shell scripts, e.g. cmdswitch2

Some people integrated my other scripts this way: https://forum.smartapfel.de/forum/thread/3134-cmdswitch2-l%C3%A4sst-homebridge-abst%C3%BCrzen/

**Comment by holovashkin** [comment]
Didn’t think that way before. Thanks a million! Will try it 🙂

**Comment by Heckie75** [comment]
I guess that this was also the reason why people  ask me also to provide status in json format. 

```
$ mipow Bedr json
{
  "device" : {
    "mac" : "A9:D5:4B:0D:AC:E6",
    "name" : "Bedroom",
    "battery" : "(not supported)",
    "vendor" : "Mipow Limited",
    "id" : "BTL201",
    "version" : "BTL201_v2",
    "software" : "Application version 2.4.3.26",
    "cpu" : "CSR101x A05"
  },
  "state" : {
    "color" : "WRGB(255,255,0,0)",
    "effect" : {
      "effect" : "halt",
      "color" : "off",
      "time" : {
        "raw" : "255",
        "human" : "n/a"
      }
    },
    "time" : "05:32"
  },
  "timer" : [
    {
      "type" : "turnon",
      "start" : "n/a",
      "runtime" : "32",
      "color" : "WRGB(0,0,0,20)"
    },
    {
      "type" : "turnon",
      "start" : "n/a",
      "runtime" : "16",
      "color" : "WRGB(0,0,60,255)"
    },
    {
      "type" : "off",
      "start" : "n/a",
      "runtime" : "5",
      "color" : "WRGB(255,255,0,0)"
    },
    {
      "type" : "turnoff",
      "start" : "06:23",
      "runtime" : "8",
      "color" : "off"
    }
  ],
  "random" : {
    "status" : "off"
  }
}
```

**Comment by holovashkin** [comment]
It took me a bit to figure everything out but now I have the playbulbs working perfectly with Siri and Home app.

I've used homebridge-cmdswitch2 plugin to make it work.
_Had a problem at first: was trying to launch commands within .exp extension and an unknown error was occurring. Switching to bulb.sh and copying the ~Known-bulbs to root folder fixed things up._ 

Thanks for your detailed help & support!

P.S. is there a way to assign a single name for 2 or more bulbs? (like bedroom could be 2 bulbs). I can probably execute 2 commands, but if there's a quick solution - it would be awesome.

**Comment by Heckie75** [comment]
No, there is no way to control two bulbs at the same time by giving the same name. The reason is that there is only one connection possible by using gatttool, which is the base of this script, at the same time.
