### ISSUE TITLE
Can't operate my "Mipow Playbulb comet smart led light strip" with my HTCU11 anymore.

### ISSUE THREAD

**Issue by FrHePo** [Heckie75/Mipow-Playbulb-BTL201#8]
After 4 months without problem I suddenly can't operate my "Mipow Playbulb comet smart led light strip" with my HTCU11 anymore. When I scan (bluetooth) for devices it shows the Playbulb comet and connects. The led strip shows full white light from the moment I plug-in the power supply. The app can't find the Playbulb anymore (after 4 months without problem) and so I can't change the led-color nor dim the led-light. That renders the whole "smart led light strip" useless :-(((    I disconnected and deinstalled the app. I restartet my HTC-U11 and reinstalled the app but it didn't change a thing.
Any suggestions?

**Comment by Heckie75** [comment]
Sorry, this repository doesn't support the Android app provided by Mipow.

This repository is meant to control smartbulb by utilizing Linux and Raspberry Pis

Of course you can use this script in order to test if the bulb works generally.

**Comment by FrHePo** [comment]
Ok. Sorry.
